version: '3.8'

services:
  opa-build:
    image: openpolicyagent/opa:latest
    command: >
      build -t wasm --v0-compatible -e item/allow_create /policies/item_policy.rego
    volumes:
      - ./src/policies:/policies
    working_dir: /policies